[tool.poetry]
name = "rag-pdf-sample"
version = "1.0.0"
description = "RAG Model Sample"
readme = "README.md"

[tool.poetry.dependencies]
streamlit = "*"
openai = "*"
dotenv = "*"
PyPDF2 = "*"
chromadb = "*"